package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyAsuntoAmbiental generated by hbm2java
 */
public class PsyAsuntoAmbiental  implements java.io.Serializable {


     private Long asamCodigo;
     private String nombre;
     private String descripcion;
     private String estadoRegistro;
     private Set<PsyDetalleErida> psyDetalleEridas = new HashSet<PsyDetalleErida>(0);

    public PsyAsuntoAmbiental() {
    }

	
    public PsyAsuntoAmbiental(Long asamCodigo, String nombre, String descripcion, String estadoRegistro) {
        this.asamCodigo = asamCodigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyAsuntoAmbiental(Long asamCodigo, String nombre, String descripcion, String estadoRegistro, Set<PsyDetalleErida> psyDetalleEridas) {
       this.asamCodigo = asamCodigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estadoRegistro = estadoRegistro;
       this.psyDetalleEridas = psyDetalleEridas;
    }
   
    public Long getAsamCodigo() {
        return this.asamCodigo;
    }
    
    public void setAsamCodigo(Long asamCodigo) {
        this.asamCodigo = asamCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyDetalleErida> getPsyDetalleEridas() {
        return this.psyDetalleEridas;
    }
    
    public void setPsyDetalleEridas(Set<PsyDetalleErida> psyDetalleEridas) {
        this.psyDetalleEridas = psyDetalleEridas;
    }




}


