package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyCiudad generated by hbm2java
 */
public class PsyCiudad  implements java.io.Serializable {


     private Long ciudCodigo;
     private PsyProvincia psyProvincia;
     private String nombre;
     private String estadoRegistro;
     private Set<PsyEmpresa> psyEmpresas = new HashSet<PsyEmpresa>(0);

    public PsyCiudad() {
    }

	
    public PsyCiudad(Long ciudCodigo, PsyProvincia psyProvincia, String nombre, String estadoRegistro) {
        this.ciudCodigo = ciudCodigo;
        this.psyProvincia = psyProvincia;
        this.nombre = nombre;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyCiudad(Long ciudCodigo, PsyProvincia psyProvincia, String nombre, String estadoRegistro, Set<PsyEmpresa> psyEmpresas) {
       this.ciudCodigo = ciudCodigo;
       this.psyProvincia = psyProvincia;
       this.nombre = nombre;
       this.estadoRegistro = estadoRegistro;
       this.psyEmpresas = psyEmpresas;
    }
   
    public Long getCiudCodigo() {
        return this.ciudCodigo;
    }
    
    public void setCiudCodigo(Long ciudCodigo) {
        this.ciudCodigo = ciudCodigo;
    }
    public PsyProvincia getPsyProvincia() {
        return this.psyProvincia;
    }
    
    public void setPsyProvincia(PsyProvincia psyProvincia) {
        this.psyProvincia = psyProvincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyEmpresa> getPsyEmpresas() {
        return this.psyEmpresas;
    }
    
    public void setPsyEmpresas(Set<PsyEmpresa> psyEmpresas) {
        this.psyEmpresas = psyEmpresas;
    }




}


