package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0



/**
 * PsyDetalleErida generated by hbm2java
 */
public class PsyDetalleErida  implements java.io.Serializable {


     private Long deerCodigo;
     private PsyMatrizErida psyMatrizErida;
     private PsyImpactoAmbiental psyImpactoAmbiental;
     private PsyAsuntoAmbiental psyAsuntoAmbiental;
     private Double peso;
     private Long calificacion;
     private Double valoracion;
     private String estadoRegistro;

    public PsyDetalleErida() {
    }

	
    public PsyDetalleErida(Long deerCodigo, PsyMatrizErida psyMatrizErida, PsyImpactoAmbiental psyImpactoAmbiental, PsyAsuntoAmbiental psyAsuntoAmbiental, Double peso, Long calificacion, String estadoRegistro) {
        this.deerCodigo = deerCodigo;
        this.psyMatrizErida = psyMatrizErida;
        this.psyImpactoAmbiental = psyImpactoAmbiental;
        this.psyAsuntoAmbiental = psyAsuntoAmbiental;
        this.peso = peso;
        this.calificacion = calificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyDetalleErida(Long deerCodigo, PsyMatrizErida psyMatrizErida, PsyImpactoAmbiental psyImpactoAmbiental, PsyAsuntoAmbiental psyAsuntoAmbiental, Double peso, Long calificacion, Double valoracion, String estadoRegistro) {
       this.deerCodigo = deerCodigo;
       this.psyMatrizErida = psyMatrizErida;
       this.psyImpactoAmbiental = psyImpactoAmbiental;
       this.psyAsuntoAmbiental = psyAsuntoAmbiental;
       this.peso = peso;
       this.calificacion = calificacion;
       this.valoracion = valoracion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getDeerCodigo() {
        return this.deerCodigo;
    }
    
    public void setDeerCodigo(Long deerCodigo) {
        this.deerCodigo = deerCodigo;
    }
    public PsyMatrizErida getPsyMatrizErida() {
        return this.psyMatrizErida;
    }
    
    public void setPsyMatrizErida(PsyMatrizErida psyMatrizErida) {
        this.psyMatrizErida = psyMatrizErida;
    }
    public PsyImpactoAmbiental getPsyImpactoAmbiental() {
        return this.psyImpactoAmbiental;
    }
    
    public void setPsyImpactoAmbiental(PsyImpactoAmbiental psyImpactoAmbiental) {
        this.psyImpactoAmbiental = psyImpactoAmbiental;
    }
    public PsyAsuntoAmbiental getPsyAsuntoAmbiental() {
        return this.psyAsuntoAmbiental;
    }
    
    public void setPsyAsuntoAmbiental(PsyAsuntoAmbiental psyAsuntoAmbiental) {
        this.psyAsuntoAmbiental = psyAsuntoAmbiental;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Long getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Long calificacion) {
        this.calificacion = calificacion;
    }
    public Double getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(Double valoracion) {
        this.valoracion = valoracion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


