package com.vortexbird.pusay.modelo;

import java.util.ArrayList;
import java.util.List;



// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0



/**
 * PsyDetalleObjetivoPlan generated by hbm2java
 */
public class PsyDetalleObjetivoPlan  implements java.io.Serializable {


     private Long dobpCodigo;
     private PsyObjetivoPlan psyObjetivoPlan;
     private PsyObjetivoEstrategico psyObjetivoEstrategico;
     private String nombre;
     private String descripcion;
     private String estadoRegistro;
     private String codigoObjetivoEstrategico;
     private String nombreObjetivoEstrategico;
     

    public PsyDetalleObjetivoPlan() {
    }

    public PsyDetalleObjetivoPlan(Long dobpCodigo, PsyObjetivoPlan psyObjetivoPlan, PsyObjetivoEstrategico psyObjetivoEstrategico, String nombre, String descripcion, String estadoRegistro) {
       this.dobpCodigo = dobpCodigo;
       this.psyObjetivoPlan = psyObjetivoPlan;
       this.psyObjetivoEstrategico = psyObjetivoEstrategico;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getDobpCodigo() {
        return this.dobpCodigo;
    }
    
    public void setDobpCodigo(Long dobpCodigo) {
        this.dobpCodigo = dobpCodigo;
    }
    public PsyObjetivoPlan getPsyObjetivoPlan() {
        return this.psyObjetivoPlan;
    }
    
    public void setPsyObjetivoPlan(PsyObjetivoPlan psyObjetivoPlan) {
        this.psyObjetivoPlan = psyObjetivoPlan;
    }
    public PsyObjetivoEstrategico getPsyObjetivoEstrategico() {
        return this.psyObjetivoEstrategico;
    }
    
    public void setPsyObjetivoEstrategico(PsyObjetivoEstrategico psyObjetivoEstrategico) {
        this.psyObjetivoEstrategico = psyObjetivoEstrategico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }

	public String getCodigoObjetivoEstrategico() {
		return codigoObjetivoEstrategico;
	}

	public void setCodigoObjetivoEstrategico(String codigoObjetivoEstrategico) {
		this.codigoObjetivoEstrategico = codigoObjetivoEstrategico;
	}

	public String getNombreObjetivoEstrategico() {
		return nombreObjetivoEstrategico;
	}

	public void setNombreObjetivoEstrategico(String nombreObjetivoEstrategico) {
		this.nombreObjetivoEstrategico = nombreObjetivoEstrategico;
	}




}


