package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyDetalleMapaEstrategico generated by hbm2java
 */
public class PsyDetalleMapaEstrategico  implements java.io.Serializable {


     private Long dmaeCodigo;
     private PsyMapaEstrategico psyMapaEstrategico;
     private PsyMatrizCorrelacion psyMatrizCorrelacion;
     private String tipo;
     private String estadoRegistro;
     private Set<PsyPlanEstrategia> psyPlanEstrategias = new HashSet<PsyPlanEstrategia>(0);

    public PsyDetalleMapaEstrategico() {
    }

	
    public PsyDetalleMapaEstrategico(Long dmaeCodigo, PsyMapaEstrategico psyMapaEstrategico, PsyMatrizCorrelacion psyMatrizCorrelacion, String estadoRegistro) {
        this.dmaeCodigo = dmaeCodigo;
        this.psyMapaEstrategico = psyMapaEstrategico;
        this.psyMatrizCorrelacion = psyMatrizCorrelacion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyDetalleMapaEstrategico(Long dmaeCodigo, PsyMapaEstrategico psyMapaEstrategico, PsyMatrizCorrelacion psyMatrizCorrelacion, String estadoRegistro, Set<PsyPlanEstrategia> psyPlanEstrategias) {
       this.dmaeCodigo = dmaeCodigo;
       this.psyMapaEstrategico = psyMapaEstrategico;
       this.psyMatrizCorrelacion = psyMatrizCorrelacion;
       this.estadoRegistro = estadoRegistro;
       this.psyPlanEstrategias = psyPlanEstrategias;
    }
   
    public PsyDetalleMapaEstrategico(Long dmaeCodigo,
			PsyMapaEstrategico psyMapaEstrategico,
			PsyMatrizCorrelacion psyMatrizCorrelacion, String tipo,
			String estadoRegistro, Set<PsyPlanEstrategia> psyPlanEstrategias) {
		super();
		this.dmaeCodigo = dmaeCodigo;
		this.psyMapaEstrategico = psyMapaEstrategico;
		this.psyMatrizCorrelacion = psyMatrizCorrelacion;
		this.tipo = tipo;
		this.estadoRegistro = estadoRegistro;
		this.psyPlanEstrategias = psyPlanEstrategias;
	}


	public Long getDmaeCodigo() {
        return this.dmaeCodigo;
    }
    
    public void setDmaeCodigo(Long dmaeCodigo) {
        this.dmaeCodigo = dmaeCodigo;
    }
    public PsyMapaEstrategico getPsyMapaEstrategico() {
        return this.psyMapaEstrategico;
    }
    
    public void setPsyMapaEstrategico(PsyMapaEstrategico psyMapaEstrategico) {
        this.psyMapaEstrategico = psyMapaEstrategico;
    }
    public PsyMatrizCorrelacion getPsyMatrizCorrelacion() {
        return this.psyMatrizCorrelacion;
    }
    
    public void setPsyMatrizCorrelacion(PsyMatrizCorrelacion psyMatrizCorrelacion) {
        this.psyMatrizCorrelacion = psyMatrizCorrelacion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyPlanEstrategia> getPsyPlanEstrategias() {
        return this.psyPlanEstrategias;
    }
    
    public void setPsyPlanEstrategias(Set<PsyPlanEstrategia> psyPlanEstrategias) {
        this.psyPlanEstrategias = psyPlanEstrategias;
    }
    
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


