package com.vortexbird.pusay.modelo;
// Generated 14-jul-2015 10:11:08 by Hibernate Tools 4.0.0



/**
 * PsyEvaluacionPeaObjetivo generated by hbm2java
 */
public class PsyEvaluacionPeaObjetivo  implements java.io.Serializable {


     private Long codigo;
     private PsyObjetivoAmbiental psyObjetivoAmbiental;
     private PsyPlanEstrategicoAmbiental psyPlanEstrategicoAmbiental;
     private Long periodo;
     private Double resultado;
     private Double historial;
     private String estadoRegistro;

    public PsyEvaluacionPeaObjetivo() {
    }

	
    public PsyEvaluacionPeaObjetivo(Long codigo, PsyObjetivoAmbiental psyObjetivoAmbiental, PsyPlanEstrategicoAmbiental psyPlanEstrategicoAmbiental, Long periodo, Double resultado, String estadoRegistro) {
        this.codigo = codigo;
        this.psyObjetivoAmbiental = psyObjetivoAmbiental;
        this.psyPlanEstrategicoAmbiental = psyPlanEstrategicoAmbiental;
        this.periodo = periodo;
        this.resultado = resultado;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyEvaluacionPeaObjetivo(Long codigo, PsyObjetivoAmbiental psyObjetivoAmbiental, PsyPlanEstrategicoAmbiental psyPlanEstrategicoAmbiental, Long periodo, Double resultado, Double historial, String estadoRegistro) {
       this.codigo = codigo;
       this.psyObjetivoAmbiental = psyObjetivoAmbiental;
       this.psyPlanEstrategicoAmbiental = psyPlanEstrategicoAmbiental;
       this.periodo = periodo;
       this.resultado = resultado;
       this.historial = historial;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
    public PsyObjetivoAmbiental getPsyObjetivoAmbiental() {
        return this.psyObjetivoAmbiental;
    }
    
    public void setPsyObjetivoAmbiental(PsyObjetivoAmbiental psyObjetivoAmbiental) {
        this.psyObjetivoAmbiental = psyObjetivoAmbiental;
    }
    public PsyPlanEstrategicoAmbiental getPsyPlanEstrategicoAmbiental() {
        return this.psyPlanEstrategicoAmbiental;
    }
    
    public void setPsyPlanEstrategicoAmbiental(PsyPlanEstrategicoAmbiental psyPlanEstrategicoAmbiental) {
        this.psyPlanEstrategicoAmbiental = psyPlanEstrategicoAmbiental;
    }
    public Long getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Long periodo) {
        this.periodo = periodo;
    }
    public Double getResultado() {
        return this.resultado;
    }
    
    public void setResultado(Double resultado) {
        this.resultado = resultado;
    }
    public Double getHistorial() {
        return this.historial;
    }
    
    public void setHistorial(Double historial) {
        this.historial = historial;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


