package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyEmpresa generated by hbm2java
 */
public class PsyEmpresa  implements java.io.Serializable {


     private Long emprCodigo;
     private PsyPersona psyPersona;
     private PsyCiudad psyCiudad;
     private String nit;
     private String nombre;
     private String direccionPrincipal;
     private Long telefonoPrincipal;
     private String estadoRegistro;
     private Set<PsyResponsable> psyResponsables = new HashSet<PsyResponsable>(0);
     private Set<PsyPlanEstrategico> psyPlanEstrategicos = new HashSet<PsyPlanEstrategico>(0);
     private Set<PsyPersona> psyPersonas = new HashSet<PsyPersona>(0);

    public PsyEmpresa() {
    }

	
    public PsyEmpresa(Long emprCodigo, PsyPersona psyPersona, PsyCiudad psyCiudad, String nit, String nombre, Long telefonoPrincipal, String estadoRegistro) {
        this.emprCodigo = emprCodigo;
        this.psyPersona = psyPersona;
        this.psyCiudad = psyCiudad;
        this.nit = nit;
        this.nombre = nombre;
        this.telefonoPrincipal = telefonoPrincipal;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyEmpresa(Long emprCodigo, PsyPersona psyPersona, PsyCiudad psyCiudad, String nit, String nombre, String direccionPrincipal, Long telefonoPrincipal, String estadoRegistro, Set<PsyResponsable> psyResponsables, Set<PsyPlanEstrategico> psyPlanEstrategicos, Set<PsyPersona> psyPersonas) {
       this.emprCodigo = emprCodigo;
       this.psyPersona = psyPersona;
       this.psyCiudad = psyCiudad;
       this.nit = nit;
       this.nombre = nombre;
       this.direccionPrincipal = direccionPrincipal;
       this.telefonoPrincipal = telefonoPrincipal;
       this.estadoRegistro = estadoRegistro;
       this.psyResponsables = psyResponsables;
       this.psyPlanEstrategicos = psyPlanEstrategicos;
       this.psyPersonas = psyPersonas;
    }
   
    public Long getEmprCodigo() {
        return this.emprCodigo;
    }
    
    public void setEmprCodigo(Long emprCodigo) {
        this.emprCodigo = emprCodigo;
    }
    public PsyPersona getPsyPersona() {
        return this.psyPersona;
    }
    
    public void setPsyPersona(PsyPersona psyPersona) {
        this.psyPersona = psyPersona;
    }
    public PsyCiudad getPsyCiudad() {
        return this.psyCiudad;
    }
    
    public void setPsyCiudad(PsyCiudad psyCiudad) {
        this.psyCiudad = psyCiudad;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccionPrincipal() {
        return this.direccionPrincipal;
    }
    
    public void setDireccionPrincipal(String direccionPrincipal) {
        this.direccionPrincipal = direccionPrincipal;
    }
    public Long getTelefonoPrincipal() {
        return this.telefonoPrincipal;
    }
    
    public void setTelefonoPrincipal(Long telefonoPrincipal) {
        this.telefonoPrincipal = telefonoPrincipal;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyResponsable> getPsyResponsables() {
        return this.psyResponsables;
    }
    
    public void setPsyResponsables(Set<PsyResponsable> psyResponsables) {
        this.psyResponsables = psyResponsables;
    }
    public Set<PsyPlanEstrategico> getPsyPlanEstrategicos() {
        return this.psyPlanEstrategicos;
    }
    
    public void setPsyPlanEstrategicos(Set<PsyPlanEstrategico> psyPlanEstrategicos) {
        this.psyPlanEstrategicos = psyPlanEstrategicos;
    }
    public Set<PsyPersona> getPsyPersonas() {
        return this.psyPersonas;
    }
    
    public void setPsyPersonas(Set<PsyPersona> psyPersonas) {
        this.psyPersonas = psyPersonas;
    }




}


