package com.vortexbird.pusay.modelo;
// Generated 14-jul-2015 10:11:08 by Hibernate Tools 4.0.0



/**
 * PsyEvaluacionPeaIndicador generated by hbm2java
 */
public class PsyEvaluacionPeaIndicador  implements java.io.Serializable {


     private Long codigo;
     private PsyPlanEstrategicoAmbiental psyPlanEstrategicoAmbiental;
     private PsyIndicador psyIndicador;
     private String multiple;
     private Long periodo;
     private Double resultado;
     private Double meta;
     private Double historial;
     private Double norma;
     private Double sectorial;
     private String estadoRegistro;

    public PsyEvaluacionPeaIndicador() {
    }

	
    public PsyEvaluacionPeaIndicador(Long codigo, PsyPlanEstrategicoAmbiental psyPlanEstrategicoAmbiental, PsyIndicador psyIndicador, Long periodo, Double resultado, Double meta, String estadoRegistro) {
        this.codigo = codigo;
        this.psyPlanEstrategicoAmbiental = psyPlanEstrategicoAmbiental;
        this.psyIndicador = psyIndicador;
        this.periodo = periodo;
        this.resultado = resultado;
        this.meta = meta;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyEvaluacionPeaIndicador(Long codigo, PsyPlanEstrategicoAmbiental psyPlanEstrategicoAmbiental, PsyIndicador psyIndicador, String multiple, Long periodo, Double resultado, Double meta, Double historial, Double norma, Double sectorial, String estadoRegistro) {
       this.codigo = codigo;
       this.psyPlanEstrategicoAmbiental = psyPlanEstrategicoAmbiental;
       this.psyIndicador = psyIndicador;
       this.multiple = multiple;
       this.periodo = periodo;
       this.resultado = resultado;
       this.meta = meta;
       this.historial = historial;
       this.norma = norma;
       this.sectorial = sectorial;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
    public PsyPlanEstrategicoAmbiental getPsyPlanEstrategicoAmbiental() {
        return this.psyPlanEstrategicoAmbiental;
    }
    
    public void setPsyPlanEstrategicoAmbiental(PsyPlanEstrategicoAmbiental psyPlanEstrategicoAmbiental) {
        this.psyPlanEstrategicoAmbiental = psyPlanEstrategicoAmbiental;
    }
    public PsyIndicador getPsyIndicador() {
        return this.psyIndicador;
    }
    
    public void setPsyIndicador(PsyIndicador psyIndicador) {
        this.psyIndicador = psyIndicador;
    }
    public String getMultiple() {
        return this.multiple;
    }
    
    public void setMultiple(String multiple) {
        this.multiple = multiple;
    }
    public Long getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Long periodo) {
        this.periodo = periodo;
    }
    public Double getResultado() {
        return this.resultado;
    }
    
    public void setResultado(Double resultado) {
        this.resultado = resultado;
    }
    public Double getMeta() {
        return this.meta;
    }
    
    public void setMeta(Double meta) {
        this.meta = meta;
    }
    public Double getHistorial() {
        return this.historial;
    }
    
    public void setHistorial(Double historial) {
        this.historial = historial;
    }
    public Double getNorma() {
        return this.norma;
    }
    
    public void setNorma(Double norma) {
        this.norma = norma;
    }
    public Double getSectorial() {
        return this.sectorial;
    }
    
    public void setSectorial(Double sectorial) {
        this.sectorial = sectorial;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


