package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyEstrategiaAmbiental generated by hbm2java
 */
public class PsyEstrategiaAmbiental  implements java.io.Serializable {


     private Long esamCodigo;
     private String nombre;
     private String descripcion;
     private String estadoRegistro;
     private Set<PsyMatrizCorrelacion> psyMatrizCorrelacions = new HashSet<PsyMatrizCorrelacion>(0);

    public PsyEstrategiaAmbiental() {
    }

	
    public PsyEstrategiaAmbiental(Long esamCodigo, String nombre, String descripcion, String estadoRegistro) {
        this.esamCodigo = esamCodigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyEstrategiaAmbiental(Long esamCodigo, String nombre, String descripcion, String estadoRegistro, Set<PsyMatrizCorrelacion> psyMatrizCorrelacions) {
       this.esamCodigo = esamCodigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estadoRegistro = estadoRegistro;
       this.psyMatrizCorrelacions = psyMatrizCorrelacions;
    }
   
    public Long getEsamCodigo() {
        return this.esamCodigo;
    }
    
    public void setEsamCodigo(Long esamCodigo) {
        this.esamCodigo = esamCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyMatrizCorrelacion> getPsyMatrizCorrelacions() {
        return this.psyMatrizCorrelacions;
    }
    
    public void setPsyMatrizCorrelacions(Set<PsyMatrizCorrelacion> psyMatrizCorrelacions) {
        this.psyMatrizCorrelacions = psyMatrizCorrelacions;
    }




}


