package com.vortexbird.pusay.modelo;
// Generated 14-jul-2015 10:11:08 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * PsyItemPresupuesto generated by hbm2java
 */
public class PsyItemPresupuesto  implements java.io.Serializable {


     private Long ipreCodigo;
     private PsyPresupuesto psyPresupuesto;
     private PsyTipoItemPresupuesto psyTipoItemPresupuesto;
     private Date fechaInicio;
     private Date fechaFin;
     private Double valorPresupuestado;
     private Double valorEjecutado;
     private Long semana;
     private String estadoRegistro;

    public PsyItemPresupuesto() {
    }

	
    public PsyItemPresupuesto(Long ipreCodigo, PsyPresupuesto psyPresupuesto, PsyTipoItemPresupuesto psyTipoItemPresupuesto, Date fechaInicio, Double valorPresupuestado, String estadoRegistro) {
        this.ipreCodigo = ipreCodigo;
        this.psyPresupuesto = psyPresupuesto;
        this.psyTipoItemPresupuesto = psyTipoItemPresupuesto;
        this.fechaInicio = fechaInicio;
        this.valorPresupuestado = valorPresupuestado;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyItemPresupuesto(Long ipreCodigo, PsyPresupuesto psyPresupuesto, PsyTipoItemPresupuesto psyTipoItemPresupuesto, Date fechaInicio, Date fechaFin, Double valorPresupuestado, Double valorEjecutado, Long semana, String estadoRegistro) {
       this.ipreCodigo = ipreCodigo;
       this.psyPresupuesto = psyPresupuesto;
       this.psyTipoItemPresupuesto = psyTipoItemPresupuesto;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.valorPresupuestado = valorPresupuestado;
       this.valorEjecutado = valorEjecutado;
       this.semana = semana;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getIpreCodigo() {
        return this.ipreCodigo;
    }
    
    public void setIpreCodigo(Long ipreCodigo) {
        this.ipreCodigo = ipreCodigo;
    }
    public PsyPresupuesto getPsyPresupuesto() {
        return this.psyPresupuesto;
    }
    
    public void setPsyPresupuesto(PsyPresupuesto psyPresupuesto) {
        this.psyPresupuesto = psyPresupuesto;
    }
    public PsyTipoItemPresupuesto getPsyTipoItemPresupuesto() {
        return this.psyTipoItemPresupuesto;
    }
    
    public void setPsyTipoItemPresupuesto(PsyTipoItemPresupuesto psyTipoItemPresupuesto) {
        this.psyTipoItemPresupuesto = psyTipoItemPresupuesto;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Double getValorPresupuestado() {
        return this.valorPresupuestado;
    }
    
    public void setValorPresupuestado(Double valorPresupuestado) {
        this.valorPresupuestado = valorPresupuestado;
    }
    public Double getValorEjecutado() {
        return this.valorEjecutado;
    }
    
    public void setValorEjecutado(Double valorEjecutado) {
        this.valorEjecutado = valorEjecutado;
    }
    public Long getSemana() {
        return this.semana;
    }
    
    public void setSemana(Long semana) {
        this.semana = semana;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


