package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PsyIpu generated by hbm2java
 */
public class PsyIpu  implements java.io.Serializable {


     private Long ipuCodigo;
     private PsyPlanAccion psyPlanAccion;
     private Date fechaInforme;
     private String periodo;
     private Date periodoFechaInicio;
     private Date periodoFechaFin;
     private String estadoIpu;
     private String estadoRegistro;
     private Double avancePresupuestado;
     private Double avanceReal;
     private String causasDesviacion;
     private String accionesPropuestas;
     private String logrosAlcanzados;
     private String logrosNoAlcanzados;
     private String tipoIpu;
     
     
    public PsyIpu() {
    }

	
    public PsyIpu(Long ipuCodigo, PsyPlanAccion psyPlanAccion, Date fechaInforme, String periodo, Date periodoFechaInicio, Date periodoFechaFin, String estadoIpu, String estadoRegistro) {
        this.ipuCodigo = ipuCodigo;
        this.psyPlanAccion = psyPlanAccion;
        this.fechaInforme = fechaInforme;
        this.periodo = periodo;
        this.periodoFechaInicio = periodoFechaInicio;
        this.periodoFechaFin = periodoFechaFin;
        this.estadoIpu = estadoIpu;
        this.estadoRegistro = estadoRegistro;
    }
   
   
    public Long getIpuCodigo() {
        return this.ipuCodigo;
    }
    
    public void setIpuCodigo(Long ipuCodigo) {
        this.ipuCodigo = ipuCodigo;
    }
    public PsyPlanAccion getPsyPlanAccion() {
        return this.psyPlanAccion;
    }
    
    public void setPsyPlanAccion(PsyPlanAccion psyPlanAccion) {
        this.psyPlanAccion = psyPlanAccion;
    }
    public Date getFechaInforme() {
        return this.fechaInforme;
    }
    
    public void setFechaInforme(Date fechaInforme) {
        this.fechaInforme = fechaInforme;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Date getPeriodoFechaInicio() {
        return this.periodoFechaInicio;
    }
    
    public void setPeriodoFechaInicio(Date periodoFechaInicio) {
        this.periodoFechaInicio = periodoFechaInicio;
    }
    public Date getPeriodoFechaFin() {
        return this.periodoFechaFin;
    }
    
    public void setPeriodoFechaFin(Date periodoFechaFin) {
        this.periodoFechaFin = periodoFechaFin;
    }
    public String getEstadoIpu() {
        return this.estadoIpu;
    }
    
    public void setEstadoIpu(String estadoIpu) {
        this.estadoIpu = estadoIpu;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }


	public Double getAvancePresupuestado() {
		return avancePresupuestado;
	}


	public void setAvancePresupuestado(Double avancePresupuestado) {
		this.avancePresupuestado = avancePresupuestado;
	}


	public Double getAvanceReal() {
		return avanceReal;
	}


	public void setAvanceReal(Double avanceReal) {
		this.avanceReal = avanceReal;
	}


	public String getCausasDesviacion() {
		return causasDesviacion;
	}


	public void setCausasDesviacion(String causasDesviacion) {
		this.causasDesviacion = causasDesviacion;
	}


	public String getAccionesPropuestas() {
		return accionesPropuestas;
	}


	public void setAccionesPropuestas(String accionesPropuestas) {
		this.accionesPropuestas = accionesPropuestas;
	}


	public String getLogrosAlcanzados() {
		return logrosAlcanzados;
	}


	public void setLogrosAlcanzados(String logrosAlcanzados) {
		this.logrosAlcanzados = logrosAlcanzados;
	}


	public String getLogrosNoAlcanzados() {
		return logrosNoAlcanzados;
	}


	public void setLogrosNoAlcanzados(String logrosNoAlcanzados) {
		this.logrosNoAlcanzados = logrosNoAlcanzados;
	}


	public String getTipoIpu() {
		return tipoIpu;
	}


	public void setTipoIpu(String tipoIpu) {
		this.tipoIpu = tipoIpu;
	}
   



}


