package com.vortexbird.pusay.modelo;
// Generated 05-ago-2015 11:08:39 by Hibernate Tools 4.0.0



/**
 * PsyImpactoObjetivo generated by hbm2java
 */
public class PsyImpactoObjetivo  implements java.io.Serializable {


     private Long imobCodigo;
     private PsyImpactoAmbiental psyImpactoAmbiental;
     private PsyObjetivoAmbiental psyObjetivoAmbiental;
     private String estadoRegistro;

    public PsyImpactoObjetivo() {
    }

    public PsyImpactoObjetivo(Long imobCodigo, PsyImpactoAmbiental psyImpactoAmbiental, PsyObjetivoAmbiental psyObjetivoAmbiental, String estadoRegistro) {
       this.imobCodigo = imobCodigo;
       this.psyImpactoAmbiental = psyImpactoAmbiental;
       this.psyObjetivoAmbiental = psyObjetivoAmbiental;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getImobCodigo() {
        return this.imobCodigo;
    }
    
    public void setImobCodigo(Long imobCodigo) {
        this.imobCodigo = imobCodigo;
    }
    public PsyImpactoAmbiental getPsyImpactoAmbiental() {
        return this.psyImpactoAmbiental;
    }
    
    public void setPsyImpactoAmbiental(PsyImpactoAmbiental psyImpactoAmbiental) {
        this.psyImpactoAmbiental = psyImpactoAmbiental;
    }
    public PsyObjetivoAmbiental getPsyObjetivoAmbiental() {
        return this.psyObjetivoAmbiental;
    }
    
    public void setPsyObjetivoAmbiental(PsyObjetivoAmbiental psyObjetivoAmbiental) {
        this.psyObjetivoAmbiental = psyObjetivoAmbiental;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


