package com.vortexbird.pusay.modelo;
// Generated 05-ago-2015 11:08:39 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyImpactoAmbiental generated by hbm2java
 */
public class PsyImpactoAmbiental  implements java.io.Serializable {


     private Long imamCodigo;
     private String nombre;
     private String descripcion;
     private String estadoRegistro;
     private Set<PsyObjetivoImpacto> psyObjetivoImpactos = new HashSet<PsyObjetivoImpacto>(0);
     private Set<PsyImpactoObjetivo> psyImpactoObjetivos = new HashSet<PsyImpactoObjetivo>(0);
     private Set<PsyMatrizCorrelacion> psyMatrizCorrelacions = new HashSet<PsyMatrizCorrelacion>(0);
     private Set<PsyTema> psyTemas = new HashSet<PsyTema>(0);
     private Set<PsyDetalleErida> psyDetalleEridas = new HashSet<PsyDetalleErida>(0);

    public PsyImpactoAmbiental() {
    }

	
    public PsyImpactoAmbiental(Long imamCodigo, String nombre, String descripcion, String estadoRegistro) {
        this.imamCodigo = imamCodigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyImpactoAmbiental(Long imamCodigo, String nombre, String descripcion, String estadoRegistro, Set<PsyObjetivoImpacto> psyObjetivoImpactos, Set<PsyImpactoObjetivo> psyImpactoObjetivos, Set<PsyMatrizCorrelacion> psyMatrizCorrelacions, Set<PsyTema> psyTemas, Set<PsyDetalleErida> psyDetalleEridas) {
       this.imamCodigo = imamCodigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estadoRegistro = estadoRegistro;
       this.psyObjetivoImpactos = psyObjetivoImpactos;
       this.psyImpactoObjetivos = psyImpactoObjetivos;
       this.psyMatrizCorrelacions = psyMatrizCorrelacions;
       this.psyTemas = psyTemas;
       this.psyDetalleEridas = psyDetalleEridas;
    }
   
    public Long getImamCodigo() {
        return this.imamCodigo;
    }
    
    public void setImamCodigo(Long imamCodigo) {
        this.imamCodigo = imamCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyObjetivoImpacto> getPsyObjetivoImpactos() {
        return this.psyObjetivoImpactos;
    }
    
    public void setPsyObjetivoImpactos(Set<PsyObjetivoImpacto> psyObjetivoImpactos) {
        this.psyObjetivoImpactos = psyObjetivoImpactos;
    }
    public Set<PsyImpactoObjetivo> getPsyImpactoObjetivos() {
        return this.psyImpactoObjetivos;
    }
    
    public void setPsyImpactoObjetivos(Set<PsyImpactoObjetivo> psyImpactoObjetivos) {
        this.psyImpactoObjetivos = psyImpactoObjetivos;
    }
    public Set<PsyMatrizCorrelacion> getPsyMatrizCorrelacions() {
        return this.psyMatrizCorrelacions;
    }
    
    public void setPsyMatrizCorrelacions(Set<PsyMatrizCorrelacion> psyMatrizCorrelacions) {
        this.psyMatrizCorrelacions = psyMatrizCorrelacions;
    }
    public Set<PsyTema> getPsyTemas() {
        return this.psyTemas;
    }
    
    public void setPsyTemas(Set<PsyTema> psyTemas) {
        this.psyTemas = psyTemas;
    }
    public Set<PsyDetalleErida> getPsyDetalleEridas() {
        return this.psyDetalleEridas;
    }
    
    public void setPsyDetalleEridas(Set<PsyDetalleErida> psyDetalleEridas) {
        this.psyDetalleEridas = psyDetalleEridas;
    }




}


