package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyMoneda generated by hbm2java
 */
public class PsyMoneda  implements java.io.Serializable {


     private Long moneCodigo;
     private String nombre;
     private String abreviatura;
     private String estadoRegistro;
     private Set<PsyPresupuesto> psyPresupuestos = new HashSet<PsyPresupuesto>(0);

    public PsyMoneda() {
    }

	
    public PsyMoneda(Long moneCodigo, String nombre, String abreviatura, String estadoRegistro) {
        this.moneCodigo = moneCodigo;
        this.nombre = nombre;
        this.abreviatura = abreviatura;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyMoneda(Long moneCodigo, String nombre, String abreviatura, String estadoRegistro, Set<PsyPresupuesto> psyPresupuestos) {
       this.moneCodigo = moneCodigo;
       this.nombre = nombre;
       this.abreviatura = abreviatura;
       this.estadoRegistro = estadoRegistro;
       this.psyPresupuestos = psyPresupuestos;
    }
   
    public Long getMoneCodigo() {
        return this.moneCodigo;
    }
    
    public void setMoneCodigo(Long moneCodigo) {
        this.moneCodigo = moneCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyPresupuesto> getPsyPresupuestos() {
        return this.psyPresupuestos;
    }
    
    public void setPsyPresupuestos(Set<PsyPresupuesto> psyPresupuestos) {
        this.psyPresupuestos = psyPresupuestos;
    }




}


