package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PsyMatrizErida generated by hbm2java
 */
public class PsyMatrizErida  implements java.io.Serializable {


     private Long maerCodigo;
     private PsyPlanEstrategico psyPlanEstrategico;
     private Date fechaInicio;
     private Date fechaFin;
     private String estadoErida;
     private String estadoRegistro;
     private Set<PsyDetalleErida> psyDetalleEridas = new HashSet<PsyDetalleErida>(0);

    public PsyMatrizErida() {
    }

	
    public PsyMatrizErida(Long maerCodigo, PsyPlanEstrategico psyPlanEstrategico, Date fechaFin, String estadoErida, String estadoRegistro) {
        this.maerCodigo = maerCodigo;
        this.psyPlanEstrategico = psyPlanEstrategico;
        this.fechaFin = fechaFin;
        this.estadoErida = estadoErida;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyMatrizErida(Long maerCodigo, PsyPlanEstrategico psyPlanEstrategico, Date fechaInicio, Date fechaFin, String estadoErida, String estadoRegistro, Set<PsyDetalleErida> psyDetalleEridas) {
       this.maerCodigo = maerCodigo;
       this.psyPlanEstrategico = psyPlanEstrategico;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estadoErida = estadoErida;
       this.estadoRegistro = estadoRegistro;
       this.psyDetalleEridas = psyDetalleEridas;
    }
   
    public Long getMaerCodigo() {
        return this.maerCodigo;
    }
    
    public void setMaerCodigo(Long maerCodigo) {
        this.maerCodigo = maerCodigo;
    }
    public PsyPlanEstrategico getPsyPlanEstrategico() {
        return this.psyPlanEstrategico;
    }
    
    public void setPsyPlanEstrategico(PsyPlanEstrategico psyPlanEstrategico) {
        this.psyPlanEstrategico = psyPlanEstrategico;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstadoErida() {
        return this.estadoErida;
    }
    
    public void setEstadoErida(String estadoErida) {
        this.estadoErida = estadoErida;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyDetalleErida> getPsyDetalleEridas() {
        return this.psyDetalleEridas;
    }
    
    public void setPsyDetalleEridas(Set<PsyDetalleErida> psyDetalleEridas) {
        this.psyDetalleEridas = psyDetalleEridas;
    }




}


