package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PsyMapaEstrategico generated by hbm2java
 */
public class PsyMapaEstrategico  implements java.io.Serializable {


     private Long maesCodigo;
     private PsyPlanEstrategico psyPlanEstrategico;
     private Date fechaInicio;
     private Date fechaFin;
     private String estadoMapaEstrategico;
     private String estadoRegistro;
     private Set<PsyDetalleMapaEstrategico> psyDetalleMapaEstrategicos = new HashSet<PsyDetalleMapaEstrategico>(0);

    public PsyMapaEstrategico() {
    }

	
    public PsyMapaEstrategico(Long maesCodigo, PsyPlanEstrategico psyPlanEstrategico, Date fechaInicio, String estadoMapaEstrategico, String estadoRegistro) {
        this.maesCodigo = maesCodigo;
        this.psyPlanEstrategico = psyPlanEstrategico;
        this.fechaInicio = fechaInicio;
        this.estadoMapaEstrategico = estadoMapaEstrategico;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyMapaEstrategico(Long maesCodigo, PsyPlanEstrategico psyPlanEstrategico, Date fechaInicio, Date fechaFin, String estadoMapaEstrategico, String estadoRegistro, Set<PsyDetalleMapaEstrategico> psyDetalleMapaEstrategicos) {
       this.maesCodigo = maesCodigo;
       this.psyPlanEstrategico = psyPlanEstrategico;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estadoMapaEstrategico = estadoMapaEstrategico;
       this.estadoRegistro = estadoRegistro;
       this.psyDetalleMapaEstrategicos = psyDetalleMapaEstrategicos;
    }
   
    public Long getMaesCodigo() {
        return this.maesCodigo;
    }
    
    public void setMaesCodigo(Long maesCodigo) {
        this.maesCodigo = maesCodigo;
    }
    public PsyPlanEstrategico getPsyPlanEstrategico() {
        return this.psyPlanEstrategico;
    }
    
    public void setPsyPlanEstrategico(PsyPlanEstrategico psyPlanEstrategico) {
        this.psyPlanEstrategico = psyPlanEstrategico;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstadoMapaEstrategico() {
        return this.estadoMapaEstrategico;
    }
    
    public void setEstadoMapaEstrategico(String estadoMapaEstrategico) {
        this.estadoMapaEstrategico = estadoMapaEstrategico;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyDetalleMapaEstrategico> getPsyDetalleMapaEstrategicos() {
        return this.psyDetalleMapaEstrategicos;
    }
    
    public void setPsyDetalleMapaEstrategicos(Set<PsyDetalleMapaEstrategico> psyDetalleMapaEstrategicos) {
        this.psyDetalleMapaEstrategicos = psyDetalleMapaEstrategicos;
    }




}


