package com.vortexbird.pusay.modelo;
// Generated 05-ago-2015 11:08:39 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyObjetivoAmbiental generated by hbm2java
 */
public class PsyObjetivoAmbiental  implements java.io.Serializable {


     private Long codigo;
     private String descripcion;
     private String estadoRegistro;
     private Set<PsyImpactoObjetivo> psyImpactoObjetivos = new HashSet<PsyImpactoObjetivo>(0);
     private Set<PsyEvaluacionPeaObjetivo> psyEvaluacionPeaObjetivos = new HashSet<PsyEvaluacionPeaObjetivo>(0);
     private Set<PsyIndicador> psyIndicadors = new HashSet<PsyIndicador>(0);

    public PsyObjetivoAmbiental() {
    }

	
    public PsyObjetivoAmbiental(Long codigo, String descripcion, String estadoRegistro) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyObjetivoAmbiental(Long codigo, String descripcion, String estadoRegistro, Set<PsyImpactoObjetivo> psyImpactoObjetivos, Set<PsyEvaluacionPeaObjetivo> psyEvaluacionPeaObjetivos, Set<PsyIndicador> psyIndicadors) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.estadoRegistro = estadoRegistro;
       this.psyImpactoObjetivos = psyImpactoObjetivos;
       this.psyEvaluacionPeaObjetivos = psyEvaluacionPeaObjetivos;
       this.psyIndicadors = psyIndicadors;
    }
   
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyImpactoObjetivo> getPsyImpactoObjetivos() {
        return this.psyImpactoObjetivos;
    }
    
    public void setPsyImpactoObjetivos(Set<PsyImpactoObjetivo> psyImpactoObjetivos) {
        this.psyImpactoObjetivos = psyImpactoObjetivos;
    }
    public Set<PsyEvaluacionPeaObjetivo> getPsyEvaluacionPeaObjetivos() {
        return this.psyEvaluacionPeaObjetivos;
    }
    
    public void setPsyEvaluacionPeaObjetivos(Set<PsyEvaluacionPeaObjetivo> psyEvaluacionPeaObjetivos) {
        this.psyEvaluacionPeaObjetivos = psyEvaluacionPeaObjetivos;
    }
    public Set<PsyIndicador> getPsyIndicadors() {
        return this.psyIndicadors;
    }
    
    public void setPsyIndicadors(Set<PsyIndicador> psyIndicadors) {
        this.psyIndicadors = psyIndicadors;
    }




}


