package com.vortexbird.pusay.modelo;
// Generated 14-jul-2015 10:11:08 by Hibernate Tools 4.0.0



/**
 * PsyObjetivoImpacto generated by hbm2java
 */
public class PsyObjetivoImpacto  implements java.io.Serializable {


     private Long obimCodigo;
     private PsyImpactoAmbiental psyImpactoAmbiental;
     private PsyObjetivoEstrategico psyObjetivoEstrategico;
     private String estadoRegistro;

    public PsyObjetivoImpacto() {
    }

	
    public PsyObjetivoImpacto(Long obimCodigo, PsyImpactoAmbiental psyImpactoAmbiental, PsyObjetivoEstrategico psyObjetivoEstrategico) {
        this.obimCodigo = obimCodigo;
        this.psyImpactoAmbiental = psyImpactoAmbiental;
        this.psyObjetivoEstrategico = psyObjetivoEstrategico;
    }
    public PsyObjetivoImpacto(Long obimCodigo, PsyImpactoAmbiental psyImpactoAmbiental, PsyObjetivoEstrategico psyObjetivoEstrategico, String estadoRegistro) {
       this.obimCodigo = obimCodigo;
       this.psyImpactoAmbiental = psyImpactoAmbiental;
       this.psyObjetivoEstrategico = psyObjetivoEstrategico;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getObimCodigo() {
        return this.obimCodigo;
    }
    
    public void setObimCodigo(Long obimCodigo) {
        this.obimCodigo = obimCodigo;
    }
    public PsyImpactoAmbiental getPsyImpactoAmbiental() {
        return this.psyImpactoAmbiental;
    }
    
    public void setPsyImpactoAmbiental(PsyImpactoAmbiental psyImpactoAmbiental) {
        this.psyImpactoAmbiental = psyImpactoAmbiental;
    }
    public PsyObjetivoEstrategico getPsyObjetivoEstrategico() {
        return this.psyObjetivoEstrategico;
    }
    
    public void setPsyObjetivoEstrategico(PsyObjetivoEstrategico psyObjetivoEstrategico) {
        this.psyObjetivoEstrategico = psyObjetivoEstrategico;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


