package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyPersona generated by hbm2java
 */
public class PsyPersona  implements java.io.Serializable {


     private Long persCodigo;
     private PsyEmpresa psyEmpresa;
     private String nombre;
     private String email;
     private Long telefono;
     private String estadoRegistro;
     private Set<PsyEmpresa> psyEmpresas = new HashSet<PsyEmpresa>(0);

    public PsyPersona() {
    }

	
    public PsyPersona(Long persCodigo, PsyEmpresa psyEmpresa, String nombre, String email, String estadoRegistro) {
        this.persCodigo = persCodigo;
        this.psyEmpresa = psyEmpresa;
        this.nombre = nombre;
        this.email = email;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyPersona(Long persCodigo, PsyEmpresa psyEmpresa, String nombre, String email, Long telefono, String estadoRegistro, Set<PsyEmpresa> psyEmpresas) {
       this.persCodigo = persCodigo;
       this.psyEmpresa = psyEmpresa;
       this.nombre = nombre;
       this.email = email;
       this.telefono = telefono;
       this.estadoRegistro = estadoRegistro;
       this.psyEmpresas = psyEmpresas;
    }
   
    public Long getPersCodigo() {
        return this.persCodigo;
    }
    
    public void setPersCodigo(Long persCodigo) {
        this.persCodigo = persCodigo;
    }
    public PsyEmpresa getPsyEmpresa() {
        return this.psyEmpresa;
    }
    
    public void setPsyEmpresa(PsyEmpresa psyEmpresa) {
        this.psyEmpresa = psyEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyEmpresa> getPsyEmpresas() {
        return this.psyEmpresas;
    }
    
    public void setPsyEmpresas(Set<PsyEmpresa> psyEmpresas) {
        this.psyEmpresas = psyEmpresas;
    }




}


