package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyPais generated by hbm2java
 */
public class PsyPais  implements java.io.Serializable {


     private Long paisCodigo;
     private String nombre;
     private String estadoRegistro;
     private Set<PsyProvincia> psyProvincias = new HashSet<PsyProvincia>(0);

    public PsyPais() {
    }

	
    public PsyPais(Long paisCodigo, String nombre, String estadoRegistro) {
        this.paisCodigo = paisCodigo;
        this.nombre = nombre;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyPais(Long paisCodigo, String nombre, String estadoRegistro, Set<PsyProvincia> psyProvincias) {
       this.paisCodigo = paisCodigo;
       this.nombre = nombre;
       this.estadoRegistro = estadoRegistro;
       this.psyProvincias = psyProvincias;
    }
   
    public Long getPaisCodigo() {
        return this.paisCodigo;
    }
    
    public void setPaisCodigo(Long paisCodigo) {
        this.paisCodigo = paisCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyProvincia> getPsyProvincias() {
        return this.psyProvincias;
    }
    
    public void setPsyProvincias(Set<PsyProvincia> psyProvincias) {
        this.psyProvincias = psyProvincias;
    }




}


