package com.vortexbird.pusay.modelo;
// Generated 14-jul-2015 10:11:08 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PsyPlanAccion generated by hbm2java
 */
public class PsyPlanAccion  implements java.io.Serializable {


     private Long placCodigo;
     private PsyPrograma psyPrograma;
     private Date fechaInicio;
     private Date fechaFinPlaneada;
     private Date fechaFinReal;
     private String nombre;
     private String descripcion;
     private String estadoPlanAccion;
     private String estadoRegistro;
     private Set<PsyTarea> psyTareas = new HashSet<PsyTarea>(0);
     private Set<PsyPresupuesto> psyPresupuestos = new HashSet<PsyPresupuesto>(0);
     private Set<PsyIpu> psyIpus = new HashSet<PsyIpu>(0);

    public PsyPlanAccion() {
    }

	
    public PsyPlanAccion(Long placCodigo, PsyPrograma psyPrograma, Date fechaInicio, Date fechaFinPlaneada, String nombre, String estadoPlanAccion, String estadoRegistro) {
        this.placCodigo = placCodigo;
        this.psyPrograma = psyPrograma;
        this.fechaInicio = fechaInicio;
        this.fechaFinPlaneada = fechaFinPlaneada;
        this.nombre = nombre;
        this.estadoPlanAccion = estadoPlanAccion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyPlanAccion(Long placCodigo, PsyPrograma psyPrograma, Date fechaInicio, Date fechaFinPlaneada, Date fechaFinReal, String nombre, String descripcion, String estadoPlanAccion, String estadoRegistro, Set<PsyTarea> psyTareas, Set<PsyPresupuesto> psyPresupuestos, Set<PsyIpu> psyIpus) {
       this.placCodigo = placCodigo;
       this.psyPrograma = psyPrograma;
       this.fechaInicio = fechaInicio;
       this.fechaFinPlaneada = fechaFinPlaneada;
       this.fechaFinReal = fechaFinReal;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estadoPlanAccion = estadoPlanAccion;
       this.estadoRegistro = estadoRegistro;
       this.psyTareas = psyTareas;
       this.psyPresupuestos = psyPresupuestos;
       this.psyIpus = psyIpus;
    }
   
    public Long getPlacCodigo() {
        return this.placCodigo;
    }
    
    public void setPlacCodigo(Long placCodigo) {
        this.placCodigo = placCodigo;
    }
    public PsyPrograma getPsyPrograma() {
        return this.psyPrograma;
    }
    
    public void setPsyPrograma(PsyPrograma psyPrograma) {
        this.psyPrograma = psyPrograma;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinPlaneada() {
        return this.fechaFinPlaneada;
    }
    
    public void setFechaFinPlaneada(Date fechaFinPlaneada) {
        this.fechaFinPlaneada = fechaFinPlaneada;
    }
    public Date getFechaFinReal() {
        return this.fechaFinReal;
    }
    
    public void setFechaFinReal(Date fechaFinReal) {
        this.fechaFinReal = fechaFinReal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoPlanAccion() {
        return this.estadoPlanAccion;
    }
    
    public void setEstadoPlanAccion(String estadoPlanAccion) {
        this.estadoPlanAccion = estadoPlanAccion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyTarea> getPsyTareas() {
        return this.psyTareas;
    }
    
    public void setPsyTareas(Set<PsyTarea> psyTareas) {
        this.psyTareas = psyTareas;
    }
    public Set<PsyPresupuesto> getPsyPresupuestos() {
        return this.psyPresupuestos;
    }
    
    public void setPsyPresupuestos(Set<PsyPresupuesto> psyPresupuestos) {
        this.psyPresupuestos = psyPresupuestos;
    }
    public Set<PsyIpu> getPsyIpus() {
        return this.psyIpus;
    }
    
    public void setPsyIpus(Set<PsyIpu> psyIpus) {
        this.psyIpus = psyIpus;
    }




}


