package com.vortexbird.pusay.modelo;
// Generated 30-abr-2015 0:40:07 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PsyPlanEstrategico generated by hbm2java
 */
public class PsyPlanEstrategico  implements java.io.Serializable {


     private Long pestCodigo;
     private PsyEmpresa psyEmpresa;
     private String nombre;
     private Date fechaInicio;
     private Date fechaFin;
     private String descripcion;
     private String estadoPlan;
     private String estadoRegistro;
     private Set<PsyObjetivoPlan> psyObjetivoPlans = new HashSet<PsyObjetivoPlan>(0);
     private Set<PsyMatrizEncuesta> psyMatrizEncuestas = new HashSet<PsyMatrizEncuesta>(0);
     private Set<PsyPlanEstrategicoAmbiental> psyPlanEstrategicoAmbientals = new HashSet<PsyPlanEstrategicoAmbiental>(0);
     private Set<PsyMatrizErida> psyMatrizEridas = new HashSet<PsyMatrizErida>(0);
     private Set<PsyMapaEstrategico> psyMapaEstrategicos = new HashSet<PsyMapaEstrategico>(0);

    public PsyPlanEstrategico() {
    }

	
    public PsyPlanEstrategico(Long pestCodigo, PsyEmpresa psyEmpresa, String nombre, Date fechaInicio, String estadoPlan, String estadoRegistro) {
        this.pestCodigo = pestCodigo;
        this.psyEmpresa = psyEmpresa;
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.estadoPlan = estadoPlan;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyPlanEstrategico(Long pestCodigo, PsyEmpresa psyEmpresa, String nombre, Date fechaInicio, Date fechaFin, String descripcion, String estadoPlan, String estadoRegistro, Set<PsyObjetivoPlan> psyObjetivoPlans, Set<PsyMatrizEncuesta> psyMatrizEncuestas, Set<PsyPlanEstrategicoAmbiental> psyPlanEstrategicoAmbientals, Set<PsyMatrizErida> psyMatrizEridas, Set<PsyMapaEstrategico> psyMapaEstrategicos) {
       this.pestCodigo = pestCodigo;
       this.psyEmpresa = psyEmpresa;
       this.nombre = nombre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.descripcion = descripcion;
       this.estadoPlan = estadoPlan;
       this.estadoRegistro = estadoRegistro;
       this.psyObjetivoPlans = psyObjetivoPlans;
       this.psyMatrizEncuestas = psyMatrizEncuestas;
       this.psyPlanEstrategicoAmbientals = psyPlanEstrategicoAmbientals;
       this.psyMatrizEridas = psyMatrizEridas;
       this.psyMapaEstrategicos = psyMapaEstrategicos;
    }
   
    public Long getPestCodigo() {
        return this.pestCodigo;
    }
    
    public void setPestCodigo(Long pestCodigo) {
        this.pestCodigo = pestCodigo;
    }
    public PsyEmpresa getPsyEmpresa() {
        return this.psyEmpresa;
    }
    
    public void setPsyEmpresa(PsyEmpresa psyEmpresa) {
        this.psyEmpresa = psyEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoPlan() {
        return this.estadoPlan;
    }
    
    public void setEstadoPlan(String estadoPlan) {
        this.estadoPlan = estadoPlan;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyObjetivoPlan> getPsyObjetivoPlans() {
        return this.psyObjetivoPlans;
    }
    
    public void setPsyObjetivoPlans(Set<PsyObjetivoPlan> psyObjetivoPlans) {
        this.psyObjetivoPlans = psyObjetivoPlans;
    }
    public Set<PsyMatrizEncuesta> getPsyMatrizEncuestas() {
        return this.psyMatrizEncuestas;
    }
    
    public void setPsyMatrizEncuestas(Set<PsyMatrizEncuesta> psyMatrizEncuestas) {
        this.psyMatrizEncuestas = psyMatrizEncuestas;
    }
    public Set<PsyPlanEstrategicoAmbiental> getPsyPlanEstrategicoAmbientals() {
        return this.psyPlanEstrategicoAmbientals;
    }
    
    public void setPsyPlanEstrategicoAmbientals(Set<PsyPlanEstrategicoAmbiental> psyPlanEstrategicoAmbientals) {
        this.psyPlanEstrategicoAmbientals = psyPlanEstrategicoAmbientals;
    }
    public Set<PsyMatrizErida> getPsyMatrizEridas() {
        return this.psyMatrizEridas;
    }
    
    public void setPsyMatrizEridas(Set<PsyMatrizErida> psyMatrizEridas) {
        this.psyMatrizEridas = psyMatrizEridas;
    }
    public Set<PsyMapaEstrategico> getPsyMapaEstrategicos() {
        return this.psyMapaEstrategicos;
    }
    
    public void setPsyMapaEstrategicos(Set<PsyMapaEstrategico> psyMapaEstrategicos) {
        this.psyMapaEstrategicos = psyMapaEstrategicos;
    }




}


