package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyProvincia generated by hbm2java
 */
public class PsyProvincia  implements java.io.Serializable {


     private Long provCodigo;
     private PsyPais psyPais;
     private String nombre;
     private String estadoRegistro;
     private Set<PsyCiudad> psyCiudads = new HashSet<PsyCiudad>(0);

    public PsyProvincia() {
    }

	
    public PsyProvincia(Long provCodigo, PsyPais psyPais, String nombre, String estadoRegistro) {
        this.provCodigo = provCodigo;
        this.psyPais = psyPais;
        this.nombre = nombre;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyProvincia(Long provCodigo, PsyPais psyPais, String nombre, String estadoRegistro, Set<PsyCiudad> psyCiudads) {
       this.provCodigo = provCodigo;
       this.psyPais = psyPais;
       this.nombre = nombre;
       this.estadoRegistro = estadoRegistro;
       this.psyCiudads = psyCiudads;
    }
   
    public Long getProvCodigo() {
        return this.provCodigo;
    }
    
    public void setProvCodigo(Long provCodigo) {
        this.provCodigo = provCodigo;
    }
    public PsyPais getPsyPais() {
        return this.psyPais;
    }
    
    public void setPsyPais(PsyPais psyPais) {
        this.psyPais = psyPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyCiudad> getPsyCiudads() {
        return this.psyCiudads;
    }
    
    public void setPsyCiudads(Set<PsyCiudad> psyCiudads) {
        this.psyCiudads = psyCiudads;
    }




}


