package com.vortexbird.pusay.modelo;
// Generated 14-jul-2015 10:11:08 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyPrograma generated by hbm2java
 */
public class PsyPrograma  implements java.io.Serializable {


     private Long progCodigo;
     private String nombre;
     private String estadoRegistro;
     private Set<PsyPlanAccion> psyPlanAccions = new HashSet<PsyPlanAccion>(0);
     private Set<PsyPlanEstrategia> psyPlanEstrategias = new HashSet<PsyPlanEstrategia>(0);

    public PsyPrograma() {
    }

	
    public PsyPrograma(Long progCodigo, String nombre) {
        this.progCodigo = progCodigo;
        this.nombre = nombre;
    }
    public PsyPrograma(Long progCodigo, String nombre, String estadoRegistro, Set<PsyPlanAccion> psyPlanAccions, Set<PsyPlanEstrategia> psyPlanEstrategias) {
       this.progCodigo = progCodigo;
       this.nombre = nombre;
       this.estadoRegistro = estadoRegistro;
       this.psyPlanAccions = psyPlanAccions;
       this.psyPlanEstrategias = psyPlanEstrategias;
    }
   
    public Long getProgCodigo() {
        return this.progCodigo;
    }
    
    public void setProgCodigo(Long progCodigo) {
        this.progCodigo = progCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyPlanAccion> getPsyPlanAccions() {
        return this.psyPlanAccions;
    }
    
    public void setPsyPlanAccions(Set<PsyPlanAccion> psyPlanAccions) {
        this.psyPlanAccions = psyPlanAccions;
    }
    public Set<PsyPlanEstrategia> getPsyPlanEstrategias() {
        return this.psyPlanEstrategias;
    }
    
    public void setPsyPlanEstrategias(Set<PsyPlanEstrategia> psyPlanEstrategias) {
        this.psyPlanEstrategias = psyPlanEstrategias;
    }




}


