package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PsyPresupuesto generated by hbm2java
 */
public class PsyPresupuesto  implements java.io.Serializable {


     private Long presCodigo;
     private PsyPlanAccion psyPlanAccion;
     private PsyMoneda psyMoneda;
     private Date fechaInicio;
     private Date fechaFin;
     private String estadoPresupuesto;
     private String estadoRegistro;
     private Set<PsyItemPresupuesto> psyItemPresupuestos = new HashSet<PsyItemPresupuesto>(0);

    public PsyPresupuesto() {
    }

	
    public PsyPresupuesto(Long presCodigo, PsyPlanAccion psyPlanAccion, PsyMoneda psyMoneda, Date fechaInicio, String estadoPresupuesto, String estadoRegistro) {
        this.presCodigo = presCodigo;
        this.psyPlanAccion = psyPlanAccion;
        this.psyMoneda = psyMoneda;
        this.fechaInicio = fechaInicio;
        this.estadoPresupuesto = estadoPresupuesto;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyPresupuesto(Long presCodigo, PsyPlanAccion psyPlanAccion, PsyMoneda psyMoneda, Date fechaInicio, Date fechaFin, String estadoPresupuesto, String estadoRegistro, Set<PsyItemPresupuesto> psyItemPresupuestos) {
       this.presCodigo = presCodigo;
       this.psyPlanAccion = psyPlanAccion;
       this.psyMoneda = psyMoneda;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estadoPresupuesto = estadoPresupuesto;
       this.estadoRegistro = estadoRegistro;
       this.psyItemPresupuestos = psyItemPresupuestos;
    }
   
    public Long getPresCodigo() {
        return this.presCodigo;
    }
    
    public void setPresCodigo(Long presCodigo) {
        this.presCodigo = presCodigo;
    }
    public PsyPlanAccion getPsyPlanAccion() {
        return this.psyPlanAccion;
    }
    
    public void setPsyPlanAccion(PsyPlanAccion psyPlanAccion) {
        this.psyPlanAccion = psyPlanAccion;
    }
    public PsyMoneda getPsyMoneda() {
        return this.psyMoneda;
    }
    
    public void setPsyMoneda(PsyMoneda psyMoneda) {
        this.psyMoneda = psyMoneda;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstadoPresupuesto() {
        return this.estadoPresupuesto;
    }
    
    public void setEstadoPresupuesto(String estadoPresupuesto) {
        this.estadoPresupuesto = estadoPresupuesto;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyItemPresupuesto> getPsyItemPresupuestos() {
        return this.psyItemPresupuestos;
    }
    
    public void setPsyItemPresupuestos(Set<PsyItemPresupuesto> psyItemPresupuestos) {
        this.psyItemPresupuestos = psyItemPresupuestos;
    }




}


