package com.vortexbird.pusay.modelo;
// Generated 21-ago-2015 9:18:21 by Hibernate Tools 4.0.0



/**
 * PsyParametro generated by hbm2java
 */
public class PsyParametro  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long paramCodigo;
     private String llave;
     private String valor;
     private String estadoRegistro;

    public PsyParametro() {
    }

    public PsyParametro(Long paramCodigo, String llave, String valor, String estadoRegistro) {
       this.paramCodigo = paramCodigo;
       this.llave = llave;
       this.valor = valor;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getParamCodigo() {
        return this.paramCodigo;
    }
    
    public void setParamCodigo(Long paramCodigo) {
        this.paramCodigo = paramCodigo;
    }
    public String getLlave() {
        return this.llave;
    }
    
    public void setLlave(String llave) {
        this.llave = llave;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


