package com.vortexbird.pusay.modelo;
// Generated 14-jul-2015 10:11:08 by Hibernate Tools 4.0.0



/**
 * PsyPlanEstrategia generated by hbm2java
 */
public class PsyPlanEstrategia  implements java.io.Serializable {


     private Long plesCodigo;
     private PsyDetalleMapaEstrategico psyDetalleMapaEstrategico;
     private PsyPrograma psyPrograma;
     private String estadoRegistro;

    public PsyPlanEstrategia() {
    }

	
    public PsyPlanEstrategia(Long plesCodigo, PsyDetalleMapaEstrategico psyDetalleMapaEstrategico, PsyPrograma psyPrograma, String estadoRegistro) {
        this.plesCodigo = plesCodigo;
        this.psyDetalleMapaEstrategico = psyDetalleMapaEstrategico;
        this.psyPrograma = psyPrograma;
        this.estadoRegistro = estadoRegistro;
    }
    public Long getPlesCodigo() {
        return this.plesCodigo;
    }
    
    public void setPlesCodigo(Long plesCodigo) {
        this.plesCodigo = plesCodigo;
    }
    public PsyDetalleMapaEstrategico getPsyDetalleMapaEstrategico() {
        return this.psyDetalleMapaEstrategico;
    }
    
    public void setPsyDetalleMapaEstrategico(PsyDetalleMapaEstrategico psyDetalleMapaEstrategico) {
        this.psyDetalleMapaEstrategico = psyDetalleMapaEstrategico;
    }
    public PsyPrograma getPsyPrograma() {
        return this.psyPrograma;
    }
    
    public void setPsyPrograma(PsyPrograma psyPrograma) {
        this.psyPrograma = psyPrograma;
    }
    
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


