package com.vortexbird.pusay.modelo;
// Generated 30-abr-2015 0:40:07 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsySubtema generated by hbm2java
 */
public class PsySubtema  implements java.io.Serializable {


     private Long codigo;
     private PsyTema psyTema;
     private String descripcion;
     private String estadoRegistro;
     private Set<PsyIndicador> psyIndicadors = new HashSet<PsyIndicador>(0);

    public PsySubtema() {
    }

	
    public PsySubtema(Long codigo, PsyTema psyTema, String descripcion, String estadoRegistro) {
        this.codigo = codigo;
        this.psyTema = psyTema;
        this.descripcion = descripcion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsySubtema(Long codigo, PsyTema psyTema, String descripcion, String estadoRegistro, Set<PsyIndicador> psyIndicadors) {
       this.codigo = codigo;
       this.psyTema = psyTema;
       this.descripcion = descripcion;
       this.estadoRegistro = estadoRegistro;
       this.psyIndicadors = psyIndicadors;
    }
   
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
    public PsyTema getPsyTema() {
        return this.psyTema;
    }
    
    public void setPsyTema(PsyTema psyTema) {
        this.psyTema = psyTema;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyIndicador> getPsyIndicadors() {
        return this.psyIndicadors;
    }
    
    public void setPsyIndicadors(Set<PsyIndicador> psyIndicadors) {
        this.psyIndicadors = psyIndicadors;
    }




}


