package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * PsySeguimientoTarea generated by hbm2java
 */
public class PsySeguimientoTarea  implements java.io.Serializable {


     private Long setaCodigo;
     private PsyTarea psyTarea;
     private String descripcion;
     private Date fecha;
     private String estadoRegistro;

    public PsySeguimientoTarea() {
    }

	
    public PsySeguimientoTarea(Long setaCodigo, PsyTarea psyTarea, String descripcion, String estadoRegistro) {
        this.setaCodigo = setaCodigo;
        this.psyTarea = psyTarea;
        this.descripcion = descripcion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsySeguimientoTarea(Long setaCodigo, PsyTarea psyTarea, String descripcion, Date fecha, String estadoRegistro) {
       this.setaCodigo = setaCodigo;
       this.psyTarea = psyTarea;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getSetaCodigo() {
        return this.setaCodigo;
    }
    
    public void setSetaCodigo(Long setaCodigo) {
        this.setaCodigo = setaCodigo;
    }
    public PsyTarea getPsyTarea() {
        return this.psyTarea;
    }
    
    public void setPsyTarea(PsyTarea psyTarea) {
        this.psyTarea = psyTarea;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


