package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PsyTarea generated by hbm2java
 */
public class PsyTarea  implements java.io.Serializable {


     private Long tareCodigo;
     private PsyResponsable psyResponsable;
     private PsyPlanAccion psyPlanAccion;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFinPlaneada;
     private Date fechaFinReal;
     private Long semanaFinPlaneada;
     private Long semanaFinReal;
     private String estadoTarea;
     private String estadoRegistro;
     private Set<PsySeguimientoTarea> psySeguimientoTareas = new HashSet<PsySeguimientoTarea>(0);

    public PsyTarea() {
    }

	
    public PsyTarea(Long tareCodigo, PsyResponsable psyResponsable, PsyPlanAccion psyPlanAccion, Date fechaInicio, Date fechaFinPlaneada, Long semanaFinPlaneada, String estadoTarea, String estadoRegistro) {
        this.tareCodigo = tareCodigo;
        this.psyResponsable = psyResponsable;
        this.psyPlanAccion = psyPlanAccion;
        this.fechaInicio = fechaInicio;
        this.fechaFinPlaneada = fechaFinPlaneada;
        this.semanaFinPlaneada = semanaFinPlaneada;
        this.estadoTarea = estadoTarea;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyTarea(Long tareCodigo, PsyResponsable psyResponsable, PsyPlanAccion psyPlanAccion, String descripcion, Date fechaInicio, Date fechaFinPlaneada, Date fechaFinReal, Long semanaFinPlaneada, Long semanaFinReal, String estadoTarea, String estadoRegistro, Set<PsySeguimientoTarea> psySeguimientoTareas) {
       this.tareCodigo = tareCodigo;
       this.psyResponsable = psyResponsable;
       this.psyPlanAccion = psyPlanAccion;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFinPlaneada = fechaFinPlaneada;
       this.fechaFinReal = fechaFinReal;
       this.semanaFinPlaneada = semanaFinPlaneada;
       this.semanaFinReal = semanaFinReal;
       this.estadoTarea = estadoTarea;
       this.estadoRegistro = estadoRegistro;
       this.psySeguimientoTareas = psySeguimientoTareas;
    }
   
    public Long getTareCodigo() {
        return this.tareCodigo;
    }
    
    public void setTareCodigo(Long tareCodigo) {
        this.tareCodigo = tareCodigo;
    }
    public PsyResponsable getPsyResponsable() {
        return this.psyResponsable;
    }
    
    public void setPsyResponsable(PsyResponsable psyResponsable) {
        this.psyResponsable = psyResponsable;
    }
    public PsyPlanAccion getPsyPlanAccion() {
        return this.psyPlanAccion;
    }
    
    public void setPsyPlanAccion(PsyPlanAccion psyPlanAccion) {
        this.psyPlanAccion = psyPlanAccion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinPlaneada() {
        return this.fechaFinPlaneada;
    }
    
    public void setFechaFinPlaneada(Date fechaFinPlaneada) {
        this.fechaFinPlaneada = fechaFinPlaneada;
    }
    public Date getFechaFinReal() {
        return this.fechaFinReal;
    }
    
    public void setFechaFinReal(Date fechaFinReal) {
        this.fechaFinReal = fechaFinReal;
    }
    public Long getSemanaFinPlaneada() {
        return this.semanaFinPlaneada;
    }
    
    public void setSemanaFinPlaneada(Long semanaFinPlaneada) {
        this.semanaFinPlaneada = semanaFinPlaneada;
    }
    public Long getSemanaFinReal() {
        return this.semanaFinReal;
    }
    
    public void setSemanaFinReal(Long semanaFinReal) {
        this.semanaFinReal = semanaFinReal;
    }
    public String getEstadoTarea() {
        return this.estadoTarea;
    }
    
    public void setEstadoTarea(String estadoTarea) {
        this.estadoTarea = estadoTarea;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsySeguimientoTarea> getPsySeguimientoTareas() {
        return this.psySeguimientoTareas;
    }
    
    public void setPsySeguimientoTareas(Set<PsySeguimientoTarea> psySeguimientoTareas) {
        this.psySeguimientoTareas = psySeguimientoTareas;
    }




}


