package com.vortexbird.pusay.modelo;
// Generated Mar 20, 2015 10:23:26 AM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyTipoItemPresupuesto generated by hbm2java
 */
public class PsyTipoItemPresupuesto  implements java.io.Serializable {


     private Long tiipCodigo;
     private String nombre;
     private String descripcion;
     private String estadoRegistro;
     private Set<PsyItemPresupuesto> psyItemPresupuestos = new HashSet<PsyItemPresupuesto>(0);

    public PsyTipoItemPresupuesto() {
    }

	
    public PsyTipoItemPresupuesto(Long tiipCodigo, String nombre, String estadoRegistro) {
        this.tiipCodigo = tiipCodigo;
        this.nombre = nombre;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyTipoItemPresupuesto(Long tiipCodigo, String nombre, String descripcion, String estadoRegistro, Set<PsyItemPresupuesto> psyItemPresupuestos) {
       this.tiipCodigo = tiipCodigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estadoRegistro = estadoRegistro;
       this.psyItemPresupuestos = psyItemPresupuestos;
    }
   
    public Long getTiipCodigo() {
        return this.tiipCodigo;
    }
    
    public void setTiipCodigo(Long tiipCodigo) {
        this.tiipCodigo = tiipCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsyItemPresupuesto> getPsyItemPresupuestos() {
        return this.psyItemPresupuestos;
    }
    
    public void setPsyItemPresupuestos(Set<PsyItemPresupuesto> psyItemPresupuestos) {
        this.psyItemPresupuestos = psyItemPresupuestos;
    }




}


