package com.vortexbird.pusay.modelo;
// Generated 30-abr-2015 0:40:07 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * PsyTema generated by hbm2java
 */
public class PsyTema  implements java.io.Serializable {


     private Long codigo;
     private PsyImpactoAmbiental psyImpactoAmbiental;
     private String descripcion;
     private String estadoRegistro;
     private Set<PsySubtema> psySubtemas = new HashSet<PsySubtema>(0);

    public PsyTema() {
    }

	
    public PsyTema(Long codigo, PsyImpactoAmbiental psyImpactoAmbiental, String descripcion, String estadoRegistro) {
        this.codigo = codigo;
        this.psyImpactoAmbiental = psyImpactoAmbiental;
        this.descripcion = descripcion;
        this.estadoRegistro = estadoRegistro;
    }
    public PsyTema(Long codigo, PsyImpactoAmbiental psyImpactoAmbiental, String descripcion, String estadoRegistro, Set<PsySubtema> psySubtemas) {
       this.codigo = codigo;
       this.psyImpactoAmbiental = psyImpactoAmbiental;
       this.descripcion = descripcion;
       this.estadoRegistro = estadoRegistro;
       this.psySubtemas = psySubtemas;
    }
   
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
    public PsyImpactoAmbiental getPsyImpactoAmbiental() {
        return this.psyImpactoAmbiental;
    }
    
    public void setPsyImpactoAmbiental(PsyImpactoAmbiental psyImpactoAmbiental) {
        this.psyImpactoAmbiental = psyImpactoAmbiental;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<PsySubtema> getPsySubtemas() {
        return this.psySubtemas;
    }
    
    public void setPsySubtemas(Set<PsySubtema> psySubtemas) {
        this.psySubtemas = psySubtemas;
    }




}


