--Inserta todas las monedas del mundo con su abreviatura
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar australiano', 'AUD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Lek albanes', 'ALL', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dinar argelino', 'DZD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Peso argentino', 'ARS', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Florin arubeño', 'AWG', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Libra esterlina', 'GBP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de las Bahamas', 'BSD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dinar de Bahrein', 'BHD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Taka de Bangladesh', 'BDT', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Barbados', 'BBD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rublo bielorruso', 'BYR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Belice', 'BZD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Bermudas', 'BMD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Ngultrum de Bhutan', 'BTN', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Boliviano', 'BOB', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Pula de Botsuana', 'BWP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Real brasileño', 'BRL', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Brunei', 'BND', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Lev bulgar', 'BGN', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco burundi', 'BIF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar canadiense', 'CAD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Yuan chino', 'CNY', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Riel camboyano', 'KHR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Escudo caboverdiano', 'CVE', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de las Islas Caiman', 'KYD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco CFA (BCEAO)', 'XOF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco CFA (BEAC)', 'XAF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Peso chileno', 'CLP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Peso colombiano', 'COP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco comorano', 'KMF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Colon costarricense', 'CRC', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Kuna croata', 'HRK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Peso cubano', 'CUP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Corona checa', 'CZK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Corona danesa', 'DKK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco yibutiano', 'DJF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Peso dominicano', 'DOP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Euro', 'EUR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar del Caribe Oriental', 'XCD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Libra egipcia', 'EGP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('El Colon del Salvador', 'SVC', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Corona estonia', 'EEK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Birr etiope', 'ETB', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Libra malvinense', 'FKP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Fiji', 'FJD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dalasi gambiano', 'GMD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Quetzal de Guatemala', 'GTQ', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco guineano', 'GNF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar guyanes', 'GYD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Cedi ghanes', 'GHS', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Hong Kong', 'HKD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Gourde haitiano', 'HTG', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Lempira hondureña', 'HNL', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Florin hungaro', 'HUF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rupia indonesia', 'IDR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rupia india', 'INR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Corona islandesa', 'ISK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rial irani', 'IRR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dinar iraqui', 'IQD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Shekel israeli', 'ILS', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Yen japones', 'JPY', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dinar jordano', 'JOD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Tenge kazako', 'KZT', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Chelin keniano', 'KES', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Won coreano', 'KRW', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dinar kuwaiti', 'KWD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Kirguistan Som', 'KGS', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Pataca de Macao', 'MOP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dinar macedonio', 'MKD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Kwacha malawiano', 'MWK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Ringgit malayo', 'MYR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rupia de Maldivas', 'MVR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Ouguiya de Mauritania', 'MRO', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rupia mauricia', 'MUR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Peso mexicano', 'MXN', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Leu moldavo', 'MDL', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Tugrik mongol', 'MNT', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dirham marroqui', 'MAD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Kyat de Myanmar', 'MMK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Namibia', 'NAD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rupia nepali', 'NPR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Guilder antillano', 'ANG', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar neozelandes', 'NZD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Cordoba nicaragüense', 'NIO', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Naira nigeriano', 'NGN', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Won de Corea del Norte', 'KPW', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Corona noruega', 'NOK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rial omani', 'OMR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco', 'CFP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rupia pakistani', 'PKR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Balboa panameño', 'PAB', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Kina de Papua Nueva Guinea', 'PGK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Guarani paraguayo', 'PYG', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Nuevo Sol peruano', 'PEN', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Peso filipino', 'PHP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Zloty polaco', 'PLN', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Riyal Qatari', 'QAR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Leu rumano', 'RON', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rublo ruso', 'RUB', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco ruandes', 'RWF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Franco suizo', 'CHF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Tala de Samoa', 'WST', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dobra de Santo Tome', 'STD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Riyal saudi', 'SAR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rupia de Seychelles', 'SCR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Leone de Sierra Leona', 'SLL', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Singapur', 'SGD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Corona eslovaca', 'SKK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de las Islas Salomon', 'SBD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Chelin somali', 'SOS', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rand sudafricano', 'ZAR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rupia de Sri Lanka', 'LKR', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Libra de Santa Helena', 'SHP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Libra sudanesa', 'SDG', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Lilangeni de Suazilandia', 'SZL', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Corona sueca', 'SEK', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Libra siria', 'SYP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Baht tailandes', 'THB', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Lira turca', 'TRY', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar taiwanes', 'TWD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Chelin tanzano', 'TZS', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Pa anga del Reino de Tonga', 'TOP', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar de Trinidad y Tobago', 'TTD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dinar tunecino', 'TND', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dolar estadounidense', 'USD', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dirham de Emiratos Arabes Unidos', 'AED', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Chelin ugandes', 'UGX', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Grivnia de Ucrania', 'UAH', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Peso uruguayo', 'UYU', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Uzbekistan Sum', 'UZS', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Vatu de Vanuatu', 'VUV', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Dong de Vietnam', 'VND', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Bolivar venezolano', 'VEF', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Rial yemeni', 'YER', 'A');
INSERT INTO psy_moneda (nombre, abreviatura, estado_registro) VALUES ('Kwacha zambiano', 'ZMK', 'A');